### ISSUE TITLE
Verify re-nomination of previously failed nominations

### ISSUE THREAD

**Issue by massar** [tridentli/trident#90] opened 2017-02-23 18:01 UTC
Verify that one can re-nominate somebody who has previously failed nominations.

This should especially be possible for admins; not so for groupmembers as the failed status is likely for a reason (timeout, but possibly rejected...)

**Comment by bapril** [comment] 2018-01-25 11:32
Closing as dupe of #107

**Closed by bapril** 2018-01-25 11:32 UTC
Labels: ack, bug, enhancement
